### ISSUE TITLE
Error: Invalid profile ps_6_2

### ISSUE THREAD

**Issue by ajmiles** [astralis3d/HLSLexplorer#3]
The tool claims that ps_6_2 is an invalid profile, but it's not. Try compiling this shader as ps_6_2 and observe the DXBC 6.0 pane says "error: invalid profile ps_6_2".

float4 main() : SV_TARGET
{
    return float4(1,0,0,1);
}

**Comment by astralis3d** [comment]
Fixed. Once I get proper libraries I will update HLSLexplorer to support SM 6.3 as well.
